using Anthropic.Models.Messages;
using LiftLog.Api.Models;
using LiftLog.Api.Service;
using LiftLog.Tests.Api.Unit.Helpers;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.SignalR.Client;
using Microsoft.Extensions.DependencyInjection;
using static LiftLog.Tests.Api.Unit.Helpers.StreamEvents;

namespace LiftLog.Tests.Api.Integration;

/// <summary>
/// Drives the real /ai-chat-v2 hub → directory → planner → SignalR path, with only
/// the Anthropic streaming seam faked, so it needs no API key.
/// </summary>
[ClassDataSource<WebApplicationFactory<Program>>(Shared = SharedType.PerClass)]
public class AiWorkoutPlannerV2IntegrationTests
{
    private const string TestWebAuthKey = "test-web-auth-key-12345";

    private static readonly int CurrentVersion = new AiPlanToolProvider().CurrentAiPlanVersion;

    private const string PlanJson = """
        {"name":"Faked Plan","description":"Generated by a faked streamer","blueprint":{"name":"Faked Plan","sessions":[{"name":"Day 1","notes":"","exercises":[{"type":"WeightedExerciseBlueprint","name":"Squat","sets":3,"repsPerSet":5,"restBetweenSets":{"minRest":"PT1M30S","maxRest":"PT3M","failureRest":"PT5M"},"supersetWithNext":false,"notes":"","link":"","progressiveOverload":{"type":"IncreaseAllEvenlyProgressiveOverload","amount":"2.5"}},{"type":"CardioExerciseBlueprint","name":"Run","sets":[{"target":{"type":"time","value":"PT20M"},"trackDuration":true,"trackDistance":false,"trackResistance":false,"trackIncline":false,"trackWeight":false,"trackSteps":false}],"notes":"","link":""}]}]}}
        """;

    private readonly WebApplicationFactory<Program> _factory;

    public AiWorkoutPlannerV2IntegrationTests(WebApplicationFactory<Program> factory)
    {
        var events = new List<RawMessageStreamEvent>
        {
            TextDelta("Here is your plan."),
            ToolUseStart("toolu_1", "create_workout_plan", index: 1),
            InputJsonDelta(PlanJson, index: 1),
            BlockStop(index: 1),
        };

        _factory = TestFactoryHelper.CreateTestFactory(
            factory,
            services =>
            {
                services.AddScoped(_ => new WebAuthPurchaseVerificationService(TestWebAuthKey));

                var mockRevenueCatService =
                    Substitute.For<IRevenueCatPurchaseVerificationService>();
                mockRevenueCatService
                    .GetUserIdHasProEntitlementAsync(Arg.Any<string>())
                    .Returns(Task.FromResult(false));
                services.AddSingleton(mockRevenueCatService);

                // Replace the Anthropic streaming seam with a scripted fake (last
                // registration wins), so no real API call is made.
                services.AddSingleton<IAnthropicMessageStreamer>(
                    new FakeAnthropicMessageStreamer(events)
                );
            }
        );
    }

    private static async Task WaitForMessageAsync(
        IReadOnlyCollection<AiChatResponseV2> messages,
        int timeoutMs = 5000
    )
    {
        var deadline = DateTime.UtcNow.AddMilliseconds(timeoutMs);
        while (messages.Count == 0 && DateTime.UtcNow < deadline)
        {
            await Task.Delay(25);
        }
    }

    private HubConnection CreateHubConnection()
    {
        var server = _factory.Server;
        return new HubConnectionBuilder()
            .WithUrl(
                $"{server.BaseAddress}ai-chat-v2",
                options =>
                {
                    options.HttpMessageHandlerFactory = _ => server.CreateHandler();
                    options.Headers.Add("Authorization", $"Web {TestWebAuthKey}");
                }
            )
            .AddJsonProtocol()
            .Build();
    }

    [Test]
    [Category("Integration")]
    public async Task SendMessage_StreamsTextThenForwardsTheGeneratedPlan()
    {
        await using var hubConnection = CreateHubConnection();
        var receivedMessages = new List<AiChatResponseV2>();
        hubConnection.On<AiChatResponseV2>("ReceiveMessage", receivedMessages.Add);

        await hubConnection.StartAsync();
        await hubConnection.InvokeAsync("SendMessage", "Make me a plan", CurrentVersion);

        // Streamed assistant prose arrives as a message response.
        await Assert
            .That(receivedMessages.OfType<AiChatMessageResponseV2>().Last().Message)
            .IsEqualTo("Here is your plan.");

        // The tool call is forwarded as a plan response with the full blueprint.
        var plan = receivedMessages.OfType<AiChatPlanResponseV2>().Single();
        await Assert.That(plan.Name).IsEqualTo("Faked Plan");
        await Assert.That(plan.Blueprint).IsNotNull();

        var exercises = plan.Blueprint!["sessions"]![0]!["exercises"]!.AsArray();
        await Assert
            .That(exercises[1]!["type"]!.GetValue<string>())
            .IsEqualTo("CardioExerciseBlueprint");
    }

    [Test]
    [Category("Integration")]
    public async Task Introduce_WhenClientOutOfDate_ReturnsUpdateRequired()
    {
        await using var hubConnection = CreateHubConnection();
        var receivedMessages = new List<AiChatResponseV2>();
        hubConnection.On<AiChatResponseV2>("ReceiveMessage", receivedMessages.Add);

        await hubConnection.StartAsync();
        // Client reports a version behind the server's current contract version.
        await hubConnection.InvokeAsync("Introduce", "en-US", CurrentVersion - 1);
        await WaitForMessageAsync(receivedMessages);

        var update = receivedMessages.OfType<AiChatUpdateRequiredResponseV2>().Single();
        await Assert.That(update.RequiredVersion).IsEqualTo(CurrentVersion);
        // No plan or intro message is generated for an out-of-date client.
        await Assert.That(receivedMessages.OfType<AiChatMessageResponseV2>().Any()).IsFalse();
    }
}
