// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Projects.Item.Offerings.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetExpandQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "package")]
        #pragma warning disable CS1591
        Package,
        #pragma warning restore CS1591
        [EnumMember(Value = "package.product")]
        #pragma warning disable CS1591
        PackageProduct,
        #pragma warning restore CS1591
    }
}
