// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EligibilityCriteria
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "google_sdk_lt_6")]
        #pragma warning disable CS1591
        Google_sdk_lt_6,
        #pragma warning restore CS1591
        [EnumMember(Value = "google_sdk_ge_6")]
        #pragma warning disable CS1591
        Google_sdk_ge_6,
        #pragma warning restore CS1591
    }
}
