// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListCustomerInvoices503Error_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "server_error")]
        #pragma warning disable CS1591
        Server_error,
        #pragma warning restore CS1591
    }
}
