// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.Cancel;
using RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.Refund;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\subscriptions\{subscription_id}\actions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refund property</summary>
        public global::RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.Refund.RefundRequestBuilder Refund
        {
            get => new global::RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.Refund.RefundRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/subscriptions/{subscription_id}/actions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Subscriptions.Item.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/subscriptions/{subscription_id}/actions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
