// <auto-generated />
using System;
using System.Collections.Generic;
using LiftLog.Backend.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LiftLog.Backend.Migrations.RateLimit
{
    [DbContext(typeof(RateLimitContext))]
    partial class RateLimitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LiftLog.Backend.Models.RateLimitConsumption", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<List<DateTimeOffset>>("Requests")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]");

                    b.HasKey("Key");

                    b.ToTable("RateLimitConsumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
