// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Projects.Item.Metrics.Overview
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetCurrencyQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "USD")]
        #pragma warning disable CS1591
        USD,
        #pragma warning restore CS1591
        [EnumMember(Value = "EUR")]
        #pragma warning disable CS1591
        EUR,
        #pragma warning restore CS1591
        [EnumMember(Value = "GBP")]
        #pragma warning disable CS1591
        GBP,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUD")]
        #pragma warning disable CS1591
        AUD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAD")]
        #pragma warning disable CS1591
        CAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "JPY")]
        #pragma warning disable CS1591
        JPY,
        #pragma warning restore CS1591
        [EnumMember(Value = "BRL")]
        #pragma warning disable CS1591
        BRL,
        #pragma warning restore CS1591
        [EnumMember(Value = "KRW")]
        #pragma warning disable CS1591
        KRW,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNY")]
        #pragma warning disable CS1591
        CNY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MXN")]
        #pragma warning disable CS1591
        MXN,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEK")]
        #pragma warning disable CS1591
        SEK,
        #pragma warning restore CS1591
        [EnumMember(Value = "PLN")]
        #pragma warning disable CS1591
        PLN,
        #pragma warning restore CS1591
    }
}
