FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY privacy.html /usr/share/nginx/html/privacy.html
COPY favicon.ico /usr/share/nginx/html/favicon.ico
COPY assets /usr/share/nginx/html/assets
