// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Projects.Item.Products.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetExpandQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "app")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
    }
}
