// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RevenueCat.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RevenueCat.Client.Projects.Item.Entitlements.Item.Products
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\entitlements\{entitlement_id}\products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/entitlements/{entitlement_id}/products{?limit*,starting_after*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/entitlements/{entitlement_id}/products{?limit*,starting_after*}", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint requires the following permission(s): &lt;code&gt;project_configuration:entitlements:read&lt;/code&gt;.
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Models.ProductsFromEntitlement"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement423Error">When receiving a 423 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ProductsFromEntitlement503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RevenueCat.Client.Models.ProductsFromEntitlement?> GetAsync(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RevenueCat.Client.Models.ProductsFromEntitlement> GetAsync(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::RevenueCat.Client.Models.ProductsFromEntitlement400Error.CreateFromDiscriminatorValue },
                { "401", global::RevenueCat.Client.Models.ProductsFromEntitlement401Error.CreateFromDiscriminatorValue },
                { "403", global::RevenueCat.Client.Models.ProductsFromEntitlement403Error.CreateFromDiscriminatorValue },
                { "404", global::RevenueCat.Client.Models.ProductsFromEntitlement404Error.CreateFromDiscriminatorValue },
                { "423", global::RevenueCat.Client.Models.ProductsFromEntitlement423Error.CreateFromDiscriminatorValue },
                { "429", global::RevenueCat.Client.Models.ProductsFromEntitlement429Error.CreateFromDiscriminatorValue },
                { "500", global::RevenueCat.Client.Models.ProductsFromEntitlement500Error.CreateFromDiscriminatorValue },
                { "503", global::RevenueCat.Client.Models.ProductsFromEntitlement503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::RevenueCat.Client.Models.ProductsFromEntitlement>(requestInfo, global::RevenueCat.Client.Models.ProductsFromEntitlement.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint requires the following permission(s): &lt;code&gt;project_configuration:entitlements:read&lt;/code&gt;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RevenueCat.Client.Projects.Item.Entitlements.Item.Products.ProductsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// This endpoint requires the following permission(s): &lt;code&gt;project_configuration:entitlements:read&lt;/code&gt;.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("limit")]
            public int? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("starting_after")]
            public string? StartingAfter { get; set; }
#nullable restore
#else
            [QueryParameter("starting_after")]
            public string StartingAfter { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
