// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using RevenueCat.Client.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace RevenueCat.Client.Projects.Item.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductsPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The ID of the app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppId { get; set; }
#nullable restore
#else
        public string AppId { get; set; }
#endif
        /// <summary>The display name of the product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The store identifier of the product.- For Apple App Store products this is the product ID of the subscription or in-app product.- For Google&apos;s Play Store, it should follow the format &apos;productId:basePlanId&apos; for subscription products and SKU for one-time purchase products.- For Stripe, the product identifier that always starts with &quot;prod_&quot;- For Amazon, if it&apos;s a subscription, the term SKU of the subscription. If it&apos;s a one-time purchase, the SKU of the product.- For Roku, this is the product identifier of the subscription or one-time purchase product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StoreIdentifier { get; set; }
#nullable restore
#else
        public string StoreIdentifier { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::RevenueCat.Client.Models.ProductType? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Products.ProductsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RevenueCat.Client.Projects.Item.Products.ProductsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::RevenueCat.Client.Projects.Item.Products.ProductsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app_id", n => { AppId = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "store_identifier", n => { StoreIdentifier = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::RevenueCat.Client.Models.ProductType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("app_id", AppId);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteStringValue("store_identifier", StoreIdentifier);
            writer.WriteEnumValue<global::RevenueCat.Client.Models.ProductType>("type", Type);
        }
    }
}
#pragma warning restore CS0618
