import {
  ProgramBlueprint,
  SessionBlueprint,
  Rest,
} from '@/models/session-models';
import BigNumber from 'bignumber.js';
import { LocalDate } from '@js-joda/core';

export const BuiltInPrograms: Record<string, ProgramBlueprint> = {
  'A303C855-9ED7-4FF8-AE60-11E9A573193E': ProgramBlueprint.fromPOJO({
    name: 'Starting Strength',
    lastEdited: LocalDate.of(2024, 1, 1),
    sessions: [
      SessionBlueprint.fromPOJO({
        name: 'Workout A',
        notes: '',
        exercises: [
          {
            name: 'Squat',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Bench Press',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Deadlift',
            sets: 1,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Workout B',
        notes: '',
        exercises: [
          {
            name: 'Squat',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Overhead Press',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Deadlift',
            sets: 1,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
    ],
  }),

  'AC80C322-3C0F-42BA-B837-CD998ADEE25A': ProgramBlueprint.fromPOJO({
    name: 'Stronglifts 5x5',
    lastEdited: LocalDate.of(2024, 1, 1),
    sessions: [
      SessionBlueprint.fromPOJO({
        name: 'Workout A',
        notes: '',
        exercises: [
          {
            name: 'Squat',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Bench Press',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Barbell Row',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Workout B',
        notes: '',
        exercises: [
          {
            name: 'Squat',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Overhead Press',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Deadlift',
            sets: 1,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
    ],
  }),

  '347607F0-67B8-4051-BFC2-3B73FCCF92D8': ProgramBlueprint.fromPOJO({
    name: 'PPL',
    lastEdited: LocalDate.of(2024, 1, 1),
    sessions: [
      SessionBlueprint.fromPOJO({
        name: 'Push',
        notes: '',
        exercises: [
          {
            name: 'Bench Press',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Overhead Press',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Tricep Extension',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Cable Fly',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Pull',
        notes: '',
        exercises: [
          {
            name: 'Deadlift',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Barbell Row',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Lat Pulldown',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Barbell Curl',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Legs',
        notes: '',
        exercises: [
          {
            name: 'Squat',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Lunges',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Leg Extension',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Leg Curl',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
    ],
  }),

  '5072C29E-1DE9-44E0-865F-F65A15E860F7': ProgramBlueprint.fromPOJO({
    name: 'PHUL',
    lastEdited: LocalDate.of(2024, 1, 1),
    sessions: [
      SessionBlueprint.fromPOJO({
        name: 'Upper Power',
        notes: '',
        exercises: [
          {
            name: 'Bench Press',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Barbell Row',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Overhead Press',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Lat Pulldown',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Barbell Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Tricep Extension',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Cable Fly',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Lower Power',
        notes: '',
        exercises: [
          {
            name: 'Squat',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Deadlift',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: new BigNumber('5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Leg Press',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Leg Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Calf Raise',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Upper Hypertrophy',
        notes: '',
        exercises: [
          {
            name: 'Incline Bench Press',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Cable Row',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Dumbbell Fly',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Lat Pulldown',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Dumbbell Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Skullcrusher',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Lower Hypertrophy',
        notes: '',
        exercises: [
          {
            name: 'Front Squat',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Romanian Deadlift',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Leg Extension',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Leg Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Calf Raise',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('2.5'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
    ],
  }),

  '0D0E0860-0555-4B43-BD93-350EDD49C6BD': ProgramBlueprint.fromPOJO({
    name: 'Light Calisthenics',
    lastEdited: LocalDate.of(2024, 1, 1),
    sessions: [
      SessionBlueprint.fromPOJO({
        name: 'Push',
        notes: '',
        exercises: [
          {
            name: 'Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Dips',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Handstand Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Pull',
        notes: '',
        exercises: [
          {
            name: 'Pullups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Chinups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Inverted Rows',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Legs',
        notes: '',
        exercises: [
          {
            name: 'Squats',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Lunges',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Calf Raises',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
    ],
  }),

  '890A285B-F883-4536-A1CE-CBC9E2D90399': ProgramBlueprint.fromPOJO({
    name: 'Heavy Calisthenics',
    lastEdited: LocalDate.of(2024, 1, 1),
    sessions: [
      SessionBlueprint.fromPOJO({
        name: 'Push',
        notes: '',
        exercises: [
          {
            name: 'Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Dips',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Handstand Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Planche Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Pull',
        notes: '',
        exercises: [
          {
            name: 'Pullups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Chinups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Inverted Rows',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Muscle Ups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
      SessionBlueprint.fromPOJO({
        name: 'Legs',
        notes: '',
        exercises: [
          {
            name: 'Squats',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Lunges',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Calf Raises',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            name: 'Pistol Squats',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: new BigNumber('0'),
            restBetweenSets: Rest.medium,
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      }),
    ],
  }),
};
