// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionsPostRequestBody : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The adjustments to the virtual currencies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody_adjustments? Adjustments { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody_adjustments Adjustments { get; set; }
#endif
        /// <summary>The reference of the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adjustments", n => { Adjustments = n.GetObjectValue<global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody_adjustments>(global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody_adjustments.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::RevenueCat.Client.Projects.Item.Customers.Item.Virtual_currencies.Transactions.TransactionsPostRequestBody_adjustments>("adjustments", Adjustments);
            writer.WriteStringValue("reference", Reference);
        }
    }
}
#pragma warning restore CS0618
