// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RevenueCat.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RevenueCat.Client.Projects.Item.Paywalls
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\paywalls
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaywallsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaywallsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/paywalls", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PaywallsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/paywalls", rawUrl)
        {
        }
        /// <summary>
        /// Create a paywall for an offering of the project. This endpoint requires the following permission(s): &lt;code&gt;project_configuration:offerings:read_write&lt;/code&gt;.
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Models.Paywall"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall409Error">When receiving a 409 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall422Error">When receiving a 422 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall423Error">When receiving a 423 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.Paywall503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RevenueCat.Client.Models.Paywall?> PostAsync(global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RevenueCat.Client.Models.Paywall> PostAsync(global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::RevenueCat.Client.Models.Paywall400Error.CreateFromDiscriminatorValue },
                { "401", global::RevenueCat.Client.Models.Paywall401Error.CreateFromDiscriminatorValue },
                { "403", global::RevenueCat.Client.Models.Paywall403Error.CreateFromDiscriminatorValue },
                { "404", global::RevenueCat.Client.Models.Paywall404Error.CreateFromDiscriminatorValue },
                { "409", global::RevenueCat.Client.Models.Paywall409Error.CreateFromDiscriminatorValue },
                { "422", global::RevenueCat.Client.Models.Paywall422Error.CreateFromDiscriminatorValue },
                { "423", global::RevenueCat.Client.Models.Paywall423Error.CreateFromDiscriminatorValue },
                { "429", global::RevenueCat.Client.Models.Paywall429Error.CreateFromDiscriminatorValue },
                { "500", global::RevenueCat.Client.Models.Paywall500Error.CreateFromDiscriminatorValue },
                { "503", global::RevenueCat.Client.Models.Paywall503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::RevenueCat.Client.Models.Paywall>(requestInfo, global::RevenueCat.Client.Models.Paywall.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a paywall for an offering of the project. This endpoint requires the following permission(s): &lt;code&gt;project_configuration:offerings:read_write&lt;/code&gt;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RevenueCat.Client.Projects.Item.Paywalls.PaywallsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
