// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using RevenueCat.Client.Models;
using RevenueCat.Client.Projects.Item.Purchases.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace RevenueCat.Client.Projects.Item.Purchases
{
    /// <summary>
    /// Builds and executes requests for operations under \projects\{project_id}\purchases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PurchasesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the RevenueCat.Client.projects.item.purchases.item collection</summary>
        /// <param name="position">ID of the purchase</param>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Purchases.Item.WithPurchase_ItemRequestBuilder"/></returns>
        public global::RevenueCat.Client.Projects.Item.Purchases.Item.WithPurchase_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("purchase_id", position);
                return new global::RevenueCat.Client.Projects.Item.Purchases.Item.WithPurchase_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PurchasesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/purchases?store_purchase_identifier={store_purchase_identifier}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PurchasesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/projects/{project_id}/purchases?store_purchase_identifier={store_purchase_identifier}", rawUrl)
        {
        }
        /// <summary>
        /// Search for a one-time purchases by any of its associated `store_purchase_identifier` values.For example, this may include the `transactionId` of any transaction in an Apple App Store purchase, or any order ID from a Google Play Store purchase. This endpoint requires the following permission(s): &lt;code&gt;customer_information:purchases:read&lt;/code&gt;.
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Models.ListPurchases"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases423Error">When receiving a 423 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases429Error">When receiving a 429 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::RevenueCat.Client.Models.ListPurchases503Error">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::RevenueCat.Client.Models.ListPurchases?> GetAsync(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder.PurchasesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::RevenueCat.Client.Models.ListPurchases> GetAsync(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder.PurchasesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::RevenueCat.Client.Models.ListPurchases400Error.CreateFromDiscriminatorValue },
                { "401", global::RevenueCat.Client.Models.ListPurchases401Error.CreateFromDiscriminatorValue },
                { "403", global::RevenueCat.Client.Models.ListPurchases403Error.CreateFromDiscriminatorValue },
                { "404", global::RevenueCat.Client.Models.ListPurchases404Error.CreateFromDiscriminatorValue },
                { "423", global::RevenueCat.Client.Models.ListPurchases423Error.CreateFromDiscriminatorValue },
                { "429", global::RevenueCat.Client.Models.ListPurchases429Error.CreateFromDiscriminatorValue },
                { "500", global::RevenueCat.Client.Models.ListPurchases500Error.CreateFromDiscriminatorValue },
                { "503", global::RevenueCat.Client.Models.ListPurchases503Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::RevenueCat.Client.Models.ListPurchases>(requestInfo, global::RevenueCat.Client.Models.ListPurchases.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Search for a one-time purchases by any of its associated `store_purchase_identifier` values.For example, this may include the `transactionId` of any transaction in an Apple App Store purchase, or any order ID from a Google Play Store purchase. This endpoint requires the following permission(s): &lt;code&gt;customer_information:purchases:read&lt;/code&gt;.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder.PurchasesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder.PurchasesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::RevenueCat.Client.Projects.Item.Purchases.PurchasesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Search for a one-time purchases by any of its associated `store_purchase_identifier` values.For example, this may include the `transactionId` of any transaction in an Apple App Store purchase, or any order ID from a Google Play Store purchase. This endpoint requires the following permission(s): &lt;code&gt;customer_information:purchases:read&lt;/code&gt;.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PurchasesRequestBuilderGetQueryParameters 
        {
            /// <summary>Store ID associated with the one-time purchase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("store_purchase_identifier")]
            public string? StorePurchaseIdentifier { get; set; }
#nullable restore
#else
            [QueryParameter("store_purchase_identifier")]
            public string StorePurchaseIdentifier { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
