// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Projects.Item.Customers.Item.Subscriptions
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetEnvironmentQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "sandbox")]
        #pragma warning disable CS1591
        Sandbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
    }
}
