// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class App : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Amazon type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_amazon? Amazon { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_amazon Amazon { get; set; }
#endif
        /// <summary>App Store type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_app_store? AppStore { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_app_store AppStore { get; set; }
#endif
        /// <summary>The date when the app was created in ms since epoch</summary>
        public long? CreatedAt { get; set; }
        /// <summary>The id of the app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Legacy Mac App Store type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_mac_app_store? MacAppStore { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_mac_app_store MacAppStore { get; set; }
#endif
        /// <summary>The name of the app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
        public global::RevenueCat.Client.Models.App_object? Object { get; set; }
        /// <summary>Paddle Billing type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_paddle? Paddle { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_paddle Paddle { get; set; }
#endif
        /// <summary>Play Store type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_play_store? PlayStore { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_play_store PlayStore { get; set; }
#endif
        /// <summary>The id of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>Revenue Cat Billing Store type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_rc_billing? RcBilling { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_rc_billing RcBilling { get; set; }
#endif
        /// <summary>Roku Channel Store type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_roku? Roku { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_roku Roku { get; set; }
#endif
        /// <summary>Stripe type details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::RevenueCat.Client.Models.App_stripe? Stripe { get; set; }
#nullable restore
#else
        public global::RevenueCat.Client.Models.App_stripe Stripe { get; set; }
#endif
        /// <summary>The platform of the app</summary>
        public global::RevenueCat.Client.Models.App_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Models.App"/> and sets the default values.
        /// </summary>
        public App()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Models.App"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RevenueCat.Client.Models.App CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::RevenueCat.Client.Models.App();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amazon", n => { Amazon = n.GetObjectValue<global::RevenueCat.Client.Models.App_amazon>(global::RevenueCat.Client.Models.App_amazon.CreateFromDiscriminatorValue); } },
                { "app_store", n => { AppStore = n.GetObjectValue<global::RevenueCat.Client.Models.App_app_store>(global::RevenueCat.Client.Models.App_app_store.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetLongValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mac_app_store", n => { MacAppStore = n.GetObjectValue<global::RevenueCat.Client.Models.App_mac_app_store>(global::RevenueCat.Client.Models.App_mac_app_store.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::RevenueCat.Client.Models.App_object>(); } },
                { "paddle", n => { Paddle = n.GetObjectValue<global::RevenueCat.Client.Models.App_paddle>(global::RevenueCat.Client.Models.App_paddle.CreateFromDiscriminatorValue); } },
                { "play_store", n => { PlayStore = n.GetObjectValue<global::RevenueCat.Client.Models.App_play_store>(global::RevenueCat.Client.Models.App_play_store.CreateFromDiscriminatorValue); } },
                { "project_id", n => { ProjectId = n.GetStringValue(); } },
                { "rc_billing", n => { RcBilling = n.GetObjectValue<global::RevenueCat.Client.Models.App_rc_billing>(global::RevenueCat.Client.Models.App_rc_billing.CreateFromDiscriminatorValue); } },
                { "roku", n => { Roku = n.GetObjectValue<global::RevenueCat.Client.Models.App_roku>(global::RevenueCat.Client.Models.App_roku.CreateFromDiscriminatorValue); } },
                { "stripe", n => { Stripe = n.GetObjectValue<global::RevenueCat.Client.Models.App_stripe>(global::RevenueCat.Client.Models.App_stripe.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::RevenueCat.Client.Models.App_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_amazon>("amazon", Amazon);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_app_store>("app_store", AppStore);
            writer.WriteLongValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_mac_app_store>("mac_app_store", MacAppStore);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::RevenueCat.Client.Models.App_object>("object", Object);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_paddle>("paddle", Paddle);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_play_store>("play_store", PlayStore);
            writer.WriteStringValue("project_id", ProjectId);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_rc_billing>("rc_billing", RcBilling);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_roku>("roku", Roku);
            writer.WriteObjectValue<global::RevenueCat.Client.Models.App_stripe>("stripe", Stripe);
            writer.WriteEnumValue<global::RevenueCat.Client.Models.App_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
