// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>The country that the object is associated with, in ISO alpha 2 code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Country
    {
        [EnumMember(Value = "null")]
        #pragma warning disable CS1591
        Null,
        #pragma warning restore CS1591
        [EnumMember(Value = "AF")]
        #pragma warning disable CS1591
        AF,
        #pragma warning restore CS1591
        [EnumMember(Value = "AL")]
        #pragma warning disable CS1591
        AL,
        #pragma warning restore CS1591
        [EnumMember(Value = "DZ")]
        #pragma warning disable CS1591
        DZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "AS")]
        #pragma warning disable CS1591
        AS,
        #pragma warning restore CS1591
        [EnumMember(Value = "AD")]
        #pragma warning disable CS1591
        AD,
        #pragma warning restore CS1591
        [EnumMember(Value = "AO")]
        #pragma warning disable CS1591
        AO,
        #pragma warning restore CS1591
        [EnumMember(Value = "AI")]
        #pragma warning disable CS1591
        AI,
        #pragma warning restore CS1591
        [EnumMember(Value = "AQ")]
        #pragma warning disable CS1591
        AQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "AG")]
        #pragma warning disable CS1591
        AG,
        #pragma warning restore CS1591
        [EnumMember(Value = "AR")]
        #pragma warning disable CS1591
        AR,
        #pragma warning restore CS1591
        [EnumMember(Value = "AM")]
        #pragma warning disable CS1591
        AM,
        #pragma warning restore CS1591
        [EnumMember(Value = "AW")]
        #pragma warning disable CS1591
        AW,
        #pragma warning restore CS1591
        [EnumMember(Value = "AU")]
        #pragma warning disable CS1591
        AU,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT")]
        #pragma warning disable CS1591
        AT,
        #pragma warning restore CS1591
        [EnumMember(Value = "AZ")]
        #pragma warning disable CS1591
        AZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "BS")]
        #pragma warning disable CS1591
        BS,
        #pragma warning restore CS1591
        [EnumMember(Value = "BH")]
        #pragma warning disable CS1591
        BH,
        #pragma warning restore CS1591
        [EnumMember(Value = "BD")]
        #pragma warning disable CS1591
        BD,
        #pragma warning restore CS1591
        [EnumMember(Value = "BB")]
        #pragma warning disable CS1591
        BB,
        #pragma warning restore CS1591
        [EnumMember(Value = "BY")]
        #pragma warning disable CS1591
        BY,
        #pragma warning restore CS1591
        [EnumMember(Value = "BE")]
        #pragma warning disable CS1591
        BE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BZ")]
        #pragma warning disable CS1591
        BZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "BJ")]
        #pragma warning disable CS1591
        BJ,
        #pragma warning restore CS1591
        [EnumMember(Value = "BM")]
        #pragma warning disable CS1591
        BM,
        #pragma warning restore CS1591
        [EnumMember(Value = "BT")]
        #pragma warning disable CS1591
        BT,
        #pragma warning restore CS1591
        [EnumMember(Value = "BO")]
        #pragma warning disable CS1591
        BO,
        #pragma warning restore CS1591
        [EnumMember(Value = "BQ")]
        #pragma warning disable CS1591
        BQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "BA")]
        #pragma warning disable CS1591
        BA,
        #pragma warning restore CS1591
        [EnumMember(Value = "BW")]
        #pragma warning disable CS1591
        BW,
        #pragma warning restore CS1591
        [EnumMember(Value = "BV")]
        #pragma warning disable CS1591
        BV,
        #pragma warning restore CS1591
        [EnumMember(Value = "BR")]
        #pragma warning disable CS1591
        BR,
        #pragma warning restore CS1591
        [EnumMember(Value = "IO")]
        #pragma warning disable CS1591
        IO,
        #pragma warning restore CS1591
        [EnumMember(Value = "BN")]
        #pragma warning disable CS1591
        BN,
        #pragma warning restore CS1591
        [EnumMember(Value = "BG")]
        #pragma warning disable CS1591
        BG,
        #pragma warning restore CS1591
        [EnumMember(Value = "BF")]
        #pragma warning disable CS1591
        BF,
        #pragma warning restore CS1591
        [EnumMember(Value = "BI")]
        #pragma warning disable CS1591
        BI,
        #pragma warning restore CS1591
        [EnumMember(Value = "CV")]
        #pragma warning disable CS1591
        CV,
        #pragma warning restore CS1591
        [EnumMember(Value = "KH")]
        #pragma warning disable CS1591
        KH,
        #pragma warning restore CS1591
        [EnumMember(Value = "CM")]
        #pragma warning disable CS1591
        CM,
        #pragma warning restore CS1591
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        CA,
        #pragma warning restore CS1591
        [EnumMember(Value = "KY")]
        #pragma warning disable CS1591
        KY,
        #pragma warning restore CS1591
        [EnumMember(Value = "CF")]
        #pragma warning disable CS1591
        CF,
        #pragma warning restore CS1591
        [EnumMember(Value = "TD")]
        #pragma warning disable CS1591
        TD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CL")]
        #pragma warning disable CS1591
        CL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CN")]
        #pragma warning disable CS1591
        CN,
        #pragma warning restore CS1591
        [EnumMember(Value = "CX")]
        #pragma warning disable CS1591
        CX,
        #pragma warning restore CS1591
        [EnumMember(Value = "CC")]
        #pragma warning disable CS1591
        CC,
        #pragma warning restore CS1591
        [EnumMember(Value = "CO")]
        #pragma warning disable CS1591
        CO,
        #pragma warning restore CS1591
        [EnumMember(Value = "KM")]
        #pragma warning disable CS1591
        KM,
        #pragma warning restore CS1591
        [EnumMember(Value = "CD")]
        #pragma warning disable CS1591
        CD,
        #pragma warning restore CS1591
        [EnumMember(Value = "CG")]
        #pragma warning disable CS1591
        CG,
        #pragma warning restore CS1591
        [EnumMember(Value = "CK")]
        #pragma warning disable CS1591
        CK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CR")]
        #pragma warning disable CS1591
        CR,
        #pragma warning restore CS1591
        [EnumMember(Value = "HR")]
        #pragma warning disable CS1591
        HR,
        #pragma warning restore CS1591
        [EnumMember(Value = "CU")]
        #pragma warning disable CS1591
        CU,
        #pragma warning restore CS1591
        [EnumMember(Value = "CW")]
        #pragma warning disable CS1591
        CW,
        #pragma warning restore CS1591
        [EnumMember(Value = "CY")]
        #pragma warning disable CS1591
        CY,
        #pragma warning restore CS1591
        [EnumMember(Value = "CZ")]
        #pragma warning disable CS1591
        CZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "CI")]
        #pragma warning disable CS1591
        CI,
        #pragma warning restore CS1591
        [EnumMember(Value = "DK")]
        #pragma warning disable CS1591
        DK,
        #pragma warning restore CS1591
        [EnumMember(Value = "DJ")]
        #pragma warning disable CS1591
        DJ,
        #pragma warning restore CS1591
        [EnumMember(Value = "DM")]
        #pragma warning disable CS1591
        DM,
        #pragma warning restore CS1591
        [EnumMember(Value = "DO")]
        #pragma warning disable CS1591
        DO,
        #pragma warning restore CS1591
        [EnumMember(Value = "EC")]
        #pragma warning disable CS1591
        EC,
        #pragma warning restore CS1591
        [EnumMember(Value = "EG")]
        #pragma warning disable CS1591
        EG,
        #pragma warning restore CS1591
        [EnumMember(Value = "SV")]
        #pragma warning disable CS1591
        SV,
        #pragma warning restore CS1591
        [EnumMember(Value = "GQ")]
        #pragma warning disable CS1591
        GQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "ER")]
        #pragma warning disable CS1591
        ER,
        #pragma warning restore CS1591
        [EnumMember(Value = "EE")]
        #pragma warning disable CS1591
        EE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SZ")]
        #pragma warning disable CS1591
        SZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "ET")]
        #pragma warning disable CS1591
        ET,
        #pragma warning restore CS1591
        [EnumMember(Value = "FK")]
        #pragma warning disable CS1591
        FK,
        #pragma warning restore CS1591
        [EnumMember(Value = "FO")]
        #pragma warning disable CS1591
        FO,
        #pragma warning restore CS1591
        [EnumMember(Value = "FJ")]
        #pragma warning disable CS1591
        FJ,
        #pragma warning restore CS1591
        [EnumMember(Value = "FI")]
        #pragma warning disable CS1591
        FI,
        #pragma warning restore CS1591
        [EnumMember(Value = "FR")]
        #pragma warning disable CS1591
        FR,
        #pragma warning restore CS1591
        [EnumMember(Value = "GF")]
        #pragma warning disable CS1591
        GF,
        #pragma warning restore CS1591
        [EnumMember(Value = "PF")]
        #pragma warning disable CS1591
        PF,
        #pragma warning restore CS1591
        [EnumMember(Value = "TF")]
        #pragma warning disable CS1591
        TF,
        #pragma warning restore CS1591
        [EnumMember(Value = "GA")]
        #pragma warning disable CS1591
        GA,
        #pragma warning restore CS1591
        [EnumMember(Value = "GM")]
        #pragma warning disable CS1591
        GM,
        #pragma warning restore CS1591
        [EnumMember(Value = "GE")]
        #pragma warning disable CS1591
        GE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DE")]
        #pragma warning disable CS1591
        DE,
        #pragma warning restore CS1591
        [EnumMember(Value = "GH")]
        #pragma warning disable CS1591
        GH,
        #pragma warning restore CS1591
        [EnumMember(Value = "GI")]
        #pragma warning disable CS1591
        GI,
        #pragma warning restore CS1591
        [EnumMember(Value = "GR")]
        #pragma warning disable CS1591
        GR,
        #pragma warning restore CS1591
        [EnumMember(Value = "GL")]
        #pragma warning disable CS1591
        GL,
        #pragma warning restore CS1591
        [EnumMember(Value = "GD")]
        #pragma warning disable CS1591
        GD,
        #pragma warning restore CS1591
        [EnumMember(Value = "GP")]
        #pragma warning disable CS1591
        GP,
        #pragma warning restore CS1591
        [EnumMember(Value = "GU")]
        #pragma warning disable CS1591
        GU,
        #pragma warning restore CS1591
        [EnumMember(Value = "GT")]
        #pragma warning disable CS1591
        GT,
        #pragma warning restore CS1591
        [EnumMember(Value = "GG")]
        #pragma warning disable CS1591
        GG,
        #pragma warning restore CS1591
        [EnumMember(Value = "GN")]
        #pragma warning disable CS1591
        GN,
        #pragma warning restore CS1591
        [EnumMember(Value = "GW")]
        #pragma warning disable CS1591
        GW,
        #pragma warning restore CS1591
        [EnumMember(Value = "GY")]
        #pragma warning disable CS1591
        GY,
        #pragma warning restore CS1591
        [EnumMember(Value = "HT")]
        #pragma warning disable CS1591
        HT,
        #pragma warning restore CS1591
        [EnumMember(Value = "HM")]
        #pragma warning disable CS1591
        HM,
        #pragma warning restore CS1591
        [EnumMember(Value = "VA")]
        #pragma warning disable CS1591
        VA,
        #pragma warning restore CS1591
        [EnumMember(Value = "HN")]
        #pragma warning disable CS1591
        HN,
        #pragma warning restore CS1591
        [EnumMember(Value = "HK")]
        #pragma warning disable CS1591
        HK,
        #pragma warning restore CS1591
        [EnumMember(Value = "HU")]
        #pragma warning disable CS1591
        HU,
        #pragma warning restore CS1591
        [EnumMember(Value = "IS")]
        #pragma warning disable CS1591
        IS,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN")]
        #pragma warning disable CS1591
        IN,
        #pragma warning restore CS1591
        [EnumMember(Value = "ID")]
        #pragma warning disable CS1591
        ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "IR")]
        #pragma warning disable CS1591
        IR,
        #pragma warning restore CS1591
        [EnumMember(Value = "IQ")]
        #pragma warning disable CS1591
        IQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "IE")]
        #pragma warning disable CS1591
        IE,
        #pragma warning restore CS1591
        [EnumMember(Value = "IM")]
        #pragma warning disable CS1591
        IM,
        #pragma warning restore CS1591
        [EnumMember(Value = "IL")]
        #pragma warning disable CS1591
        IL,
        #pragma warning restore CS1591
        [EnumMember(Value = "IT")]
        #pragma warning disable CS1591
        IT,
        #pragma warning restore CS1591
        [EnumMember(Value = "JM")]
        #pragma warning disable CS1591
        JM,
        #pragma warning restore CS1591
        [EnumMember(Value = "JP")]
        #pragma warning disable CS1591
        JP,
        #pragma warning restore CS1591
        [EnumMember(Value = "JE")]
        #pragma warning disable CS1591
        JE,
        #pragma warning restore CS1591
        [EnumMember(Value = "JO")]
        #pragma warning disable CS1591
        JO,
        #pragma warning restore CS1591
        [EnumMember(Value = "KZ")]
        #pragma warning disable CS1591
        KZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "KE")]
        #pragma warning disable CS1591
        KE,
        #pragma warning restore CS1591
        [EnumMember(Value = "KI")]
        #pragma warning disable CS1591
        KI,
        #pragma warning restore CS1591
        [EnumMember(Value = "KP")]
        #pragma warning disable CS1591
        KP,
        #pragma warning restore CS1591
        [EnumMember(Value = "KR")]
        #pragma warning disable CS1591
        KR,
        #pragma warning restore CS1591
        [EnumMember(Value = "KW")]
        #pragma warning disable CS1591
        KW,
        #pragma warning restore CS1591
        [EnumMember(Value = "KG")]
        #pragma warning disable CS1591
        KG,
        #pragma warning restore CS1591
        [EnumMember(Value = "LA")]
        #pragma warning disable CS1591
        LA,
        #pragma warning restore CS1591
        [EnumMember(Value = "LV")]
        #pragma warning disable CS1591
        LV,
        #pragma warning restore CS1591
        [EnumMember(Value = "LB")]
        #pragma warning disable CS1591
        LB,
        #pragma warning restore CS1591
        [EnumMember(Value = "LS")]
        #pragma warning disable CS1591
        LS,
        #pragma warning restore CS1591
        [EnumMember(Value = "LR")]
        #pragma warning disable CS1591
        LR,
        #pragma warning restore CS1591
        [EnumMember(Value = "LY")]
        #pragma warning disable CS1591
        LY,
        #pragma warning restore CS1591
        [EnumMember(Value = "LI")]
        #pragma warning disable CS1591
        LI,
        #pragma warning restore CS1591
        [EnumMember(Value = "LT")]
        #pragma warning disable CS1591
        LT,
        #pragma warning restore CS1591
        [EnumMember(Value = "LU")]
        #pragma warning disable CS1591
        LU,
        #pragma warning restore CS1591
        [EnumMember(Value = "MO")]
        #pragma warning disable CS1591
        MO,
        #pragma warning restore CS1591
        [EnumMember(Value = "MG")]
        #pragma warning disable CS1591
        MG,
        #pragma warning restore CS1591
        [EnumMember(Value = "MW")]
        #pragma warning disable CS1591
        MW,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY")]
        #pragma warning disable CS1591
        MY,
        #pragma warning restore CS1591
        [EnumMember(Value = "MV")]
        #pragma warning disable CS1591
        MV,
        #pragma warning restore CS1591
        [EnumMember(Value = "ML")]
        #pragma warning disable CS1591
        ML,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT")]
        #pragma warning disable CS1591
        MT,
        #pragma warning restore CS1591
        [EnumMember(Value = "MH")]
        #pragma warning disable CS1591
        MH,
        #pragma warning restore CS1591
        [EnumMember(Value = "MQ")]
        #pragma warning disable CS1591
        MQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "MR")]
        #pragma warning disable CS1591
        MR,
        #pragma warning restore CS1591
        [EnumMember(Value = "MU")]
        #pragma warning disable CS1591
        MU,
        #pragma warning restore CS1591
        [EnumMember(Value = "YT")]
        #pragma warning disable CS1591
        YT,
        #pragma warning restore CS1591
        [EnumMember(Value = "MX")]
        #pragma warning disable CS1591
        MX,
        #pragma warning restore CS1591
        [EnumMember(Value = "FM")]
        #pragma warning disable CS1591
        FM,
        #pragma warning restore CS1591
        [EnumMember(Value = "MD")]
        #pragma warning disable CS1591
        MD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MC")]
        #pragma warning disable CS1591
        MC,
        #pragma warning restore CS1591
        [EnumMember(Value = "MN")]
        #pragma warning disable CS1591
        MN,
        #pragma warning restore CS1591
        [EnumMember(Value = "ME")]
        #pragma warning disable CS1591
        ME,
        #pragma warning restore CS1591
        [EnumMember(Value = "MS")]
        #pragma warning disable CS1591
        MS,
        #pragma warning restore CS1591
        [EnumMember(Value = "MA")]
        #pragma warning disable CS1591
        MA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MZ")]
        #pragma warning disable CS1591
        MZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "MM")]
        #pragma warning disable CS1591
        MM,
        #pragma warning restore CS1591
        [EnumMember(Value = "NA")]
        #pragma warning disable CS1591
        NA,
        #pragma warning restore CS1591
        [EnumMember(Value = "NR")]
        #pragma warning disable CS1591
        NR,
        #pragma warning restore CS1591
        [EnumMember(Value = "NP")]
        #pragma warning disable CS1591
        NP,
        #pragma warning restore CS1591
        [EnumMember(Value = "NL")]
        #pragma warning disable CS1591
        NL,
        #pragma warning restore CS1591
        [EnumMember(Value = "NC")]
        #pragma warning disable CS1591
        NC,
        #pragma warning restore CS1591
        [EnumMember(Value = "NZ")]
        #pragma warning disable CS1591
        NZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "NI")]
        #pragma warning disable CS1591
        NI,
        #pragma warning restore CS1591
        [EnumMember(Value = "NE")]
        #pragma warning disable CS1591
        NE,
        #pragma warning restore CS1591
        [EnumMember(Value = "NG")]
        #pragma warning disable CS1591
        NG,
        #pragma warning restore CS1591
        [EnumMember(Value = "NU")]
        #pragma warning disable CS1591
        NU,
        #pragma warning restore CS1591
        [EnumMember(Value = "NF")]
        #pragma warning disable CS1591
        NF,
        #pragma warning restore CS1591
        [EnumMember(Value = "MP")]
        #pragma warning disable CS1591
        MP,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO")]
        #pragma warning disable CS1591
        NO,
        #pragma warning restore CS1591
        [EnumMember(Value = "OM")]
        #pragma warning disable CS1591
        OM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PK")]
        #pragma warning disable CS1591
        PK,
        #pragma warning restore CS1591
        [EnumMember(Value = "PW")]
        #pragma warning disable CS1591
        PW,
        #pragma warning restore CS1591
        [EnumMember(Value = "PS")]
        #pragma warning disable CS1591
        PS,
        #pragma warning restore CS1591
        [EnumMember(Value = "PA")]
        #pragma warning disable CS1591
        PA,
        #pragma warning restore CS1591
        [EnumMember(Value = "PG")]
        #pragma warning disable CS1591
        PG,
        #pragma warning restore CS1591
        [EnumMember(Value = "PY")]
        #pragma warning disable CS1591
        PY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PE")]
        #pragma warning disable CS1591
        PE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PH")]
        #pragma warning disable CS1591
        PH,
        #pragma warning restore CS1591
        [EnumMember(Value = "PN")]
        #pragma warning disable CS1591
        PN,
        #pragma warning restore CS1591
        [EnumMember(Value = "PL")]
        #pragma warning disable CS1591
        PL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PT")]
        #pragma warning disable CS1591
        PT,
        #pragma warning restore CS1591
        [EnumMember(Value = "PR")]
        #pragma warning disable CS1591
        PR,
        #pragma warning restore CS1591
        [EnumMember(Value = "QA")]
        #pragma warning disable CS1591
        QA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MK")]
        #pragma warning disable CS1591
        MK,
        #pragma warning restore CS1591
        [EnumMember(Value = "RO")]
        #pragma warning disable CS1591
        RO,
        #pragma warning restore CS1591
        [EnumMember(Value = "RU")]
        #pragma warning disable CS1591
        RU,
        #pragma warning restore CS1591
        [EnumMember(Value = "RW")]
        #pragma warning disable CS1591
        RW,
        #pragma warning restore CS1591
        [EnumMember(Value = "RE")]
        #pragma warning disable CS1591
        RE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BL")]
        #pragma warning disable CS1591
        BL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SH")]
        #pragma warning disable CS1591
        SH,
        #pragma warning restore CS1591
        [EnumMember(Value = "KN")]
        #pragma warning disable CS1591
        KN,
        #pragma warning restore CS1591
        [EnumMember(Value = "LC")]
        #pragma warning disable CS1591
        LC,
        #pragma warning restore CS1591
        [EnumMember(Value = "MF")]
        #pragma warning disable CS1591
        MF,
        #pragma warning restore CS1591
        [EnumMember(Value = "PM")]
        #pragma warning disable CS1591
        PM,
        #pragma warning restore CS1591
        [EnumMember(Value = "VC")]
        #pragma warning disable CS1591
        VC,
        #pragma warning restore CS1591
        [EnumMember(Value = "WS")]
        #pragma warning disable CS1591
        WS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SM")]
        #pragma warning disable CS1591
        SM,
        #pragma warning restore CS1591
        [EnumMember(Value = "ST")]
        #pragma warning disable CS1591
        ST,
        #pragma warning restore CS1591
        [EnumMember(Value = "SA")]
        #pragma warning disable CS1591
        SA,
        #pragma warning restore CS1591
        [EnumMember(Value = "SN")]
        #pragma warning disable CS1591
        SN,
        #pragma warning restore CS1591
        [EnumMember(Value = "RS")]
        #pragma warning disable CS1591
        RS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SC")]
        #pragma warning disable CS1591
        SC,
        #pragma warning restore CS1591
        [EnumMember(Value = "SL")]
        #pragma warning disable CS1591
        SL,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG")]
        #pragma warning disable CS1591
        SG,
        #pragma warning restore CS1591
        [EnumMember(Value = "SX")]
        #pragma warning disable CS1591
        SX,
        #pragma warning restore CS1591
        [EnumMember(Value = "SK")]
        #pragma warning disable CS1591
        SK,
        #pragma warning restore CS1591
        [EnumMember(Value = "SI")]
        #pragma warning disable CS1591
        SI,
        #pragma warning restore CS1591
        [EnumMember(Value = "SB")]
        #pragma warning disable CS1591
        SB,
        #pragma warning restore CS1591
        [EnumMember(Value = "SO")]
        #pragma warning disable CS1591
        SO,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZA")]
        #pragma warning disable CS1591
        ZA,
        #pragma warning restore CS1591
        [EnumMember(Value = "GS")]
        #pragma warning disable CS1591
        GS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SS")]
        #pragma warning disable CS1591
        SS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ES")]
        #pragma warning disable CS1591
        ES,
        #pragma warning restore CS1591
        [EnumMember(Value = "LK")]
        #pragma warning disable CS1591
        LK,
        #pragma warning restore CS1591
        [EnumMember(Value = "SD")]
        #pragma warning disable CS1591
        SD,
        #pragma warning restore CS1591
        [EnumMember(Value = "SR")]
        #pragma warning disable CS1591
        SR,
        #pragma warning restore CS1591
        [EnumMember(Value = "SJ")]
        #pragma warning disable CS1591
        SJ,
        #pragma warning restore CS1591
        [EnumMember(Value = "SE")]
        #pragma warning disable CS1591
        SE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CH")]
        #pragma warning disable CS1591
        CH,
        #pragma warning restore CS1591
        [EnumMember(Value = "SY")]
        #pragma warning disable CS1591
        SY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TW")]
        #pragma warning disable CS1591
        TW,
        #pragma warning restore CS1591
        [EnumMember(Value = "TJ")]
        #pragma warning disable CS1591
        TJ,
        #pragma warning restore CS1591
        [EnumMember(Value = "TZ")]
        #pragma warning disable CS1591
        TZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "TH")]
        #pragma warning disable CS1591
        TH,
        #pragma warning restore CS1591
        [EnumMember(Value = "TL")]
        #pragma warning disable CS1591
        TL,
        #pragma warning restore CS1591
        [EnumMember(Value = "TG")]
        #pragma warning disable CS1591
        TG,
        #pragma warning restore CS1591
        [EnumMember(Value = "TK")]
        #pragma warning disable CS1591
        TK,
        #pragma warning restore CS1591
        [EnumMember(Value = "TO")]
        #pragma warning disable CS1591
        TO,
        #pragma warning restore CS1591
        [EnumMember(Value = "TT")]
        #pragma warning disable CS1591
        TT,
        #pragma warning restore CS1591
        [EnumMember(Value = "TN")]
        #pragma warning disable CS1591
        TN,
        #pragma warning restore CS1591
        [EnumMember(Value = "TR")]
        #pragma warning disable CS1591
        TR,
        #pragma warning restore CS1591
        [EnumMember(Value = "TM")]
        #pragma warning disable CS1591
        TM,
        #pragma warning restore CS1591
        [EnumMember(Value = "TC")]
        #pragma warning disable CS1591
        TC,
        #pragma warning restore CS1591
        [EnumMember(Value = "TV")]
        #pragma warning disable CS1591
        TV,
        #pragma warning restore CS1591
        [EnumMember(Value = "UG")]
        #pragma warning disable CS1591
        UG,
        #pragma warning restore CS1591
        [EnumMember(Value = "UA")]
        #pragma warning disable CS1591
        UA,
        #pragma warning restore CS1591
        [EnumMember(Value = "AE")]
        #pragma warning disable CS1591
        AE,
        #pragma warning restore CS1591
        [EnumMember(Value = "GB")]
        #pragma warning disable CS1591
        GB,
        #pragma warning restore CS1591
        [EnumMember(Value = "UM")]
        #pragma warning disable CS1591
        UM,
        #pragma warning restore CS1591
        [EnumMember(Value = "US")]
        #pragma warning disable CS1591
        US,
        #pragma warning restore CS1591
        [EnumMember(Value = "UY")]
        #pragma warning disable CS1591
        UY,
        #pragma warning restore CS1591
        [EnumMember(Value = "UZ")]
        #pragma warning disable CS1591
        UZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "VU")]
        #pragma warning disable CS1591
        VU,
        #pragma warning restore CS1591
        [EnumMember(Value = "VE")]
        #pragma warning disable CS1591
        VE,
        #pragma warning restore CS1591
        [EnumMember(Value = "VN")]
        #pragma warning disable CS1591
        VN,
        #pragma warning restore CS1591
        [EnumMember(Value = "VG")]
        #pragma warning disable CS1591
        VG,
        #pragma warning restore CS1591
        [EnumMember(Value = "VI")]
        #pragma warning disable CS1591
        VI,
        #pragma warning restore CS1591
        [EnumMember(Value = "WF")]
        #pragma warning disable CS1591
        WF,
        #pragma warning restore CS1591
        [EnumMember(Value = "EH")]
        #pragma warning disable CS1591
        EH,
        #pragma warning restore CS1591
        [EnumMember(Value = "YE")]
        #pragma warning disable CS1591
        YE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZM")]
        #pragma warning disable CS1591
        ZM,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZW")]
        #pragma warning disable CS1591
        ZW,
        #pragma warning restore CS1591
        [EnumMember(Value = "AX")]
        #pragma warning disable CS1591
        AX,
        #pragma warning restore CS1591
    }
}
