// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>The subscription duration period</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateAppStoreConnectSubscriptionInput_duration
    {
        [EnumMember(Value = "ONE_WEEK")]
        #pragma warning disable CS1591
        ONE_WEEK,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONE_MONTH")]
        #pragma warning disable CS1591
        ONE_MONTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "TWO_MONTHS")]
        #pragma warning disable CS1591
        TWO_MONTHS,
        #pragma warning restore CS1591
        [EnumMember(Value = "THREE_MONTHS")]
        #pragma warning disable CS1591
        THREE_MONTHS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIX_MONTHS")]
        #pragma warning disable CS1591
        SIX_MONTHS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ONE_YEAR")]
        #pragma warning disable CS1591
        ONE_YEAR,
        #pragma warning restore CS1591
    }
}
