// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateAppStoreConnectSubscriptionInput : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The subscription duration period</summary>
        public global::RevenueCat.Client.Models.CreateAppStoreConnectSubscriptionInput_duration? Duration { get; set; }
        /// <summary>The ID of the subscription group (optional)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionGroupId { get; set; }
#nullable restore
#else
        public string SubscriptionGroupId { get; set; }
#endif
        /// <summary>The name of the subscription group</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubscriptionGroupName { get; set; }
#nullable restore
#else
        public string SubscriptionGroupName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Models.CreateAppStoreConnectSubscriptionInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RevenueCat.Client.Models.CreateAppStoreConnectSubscriptionInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::RevenueCat.Client.Models.CreateAppStoreConnectSubscriptionInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "duration", n => { Duration = n.GetEnumValue<global::RevenueCat.Client.Models.CreateAppStoreConnectSubscriptionInput_duration>(); } },
                { "subscription_group_id", n => { SubscriptionGroupId = n.GetStringValue(); } },
                { "subscription_group_name", n => { SubscriptionGroupName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::RevenueCat.Client.Models.CreateAppStoreConnectSubscriptionInput_duration>("duration", Duration);
            writer.WriteStringValue("subscription_group_id", SubscriptionGroupId);
            writer.WriteStringValue("subscription_group_name", SubscriptionGroupName);
        }
    }
}
#pragma warning restore CS0618
