// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>The type of the deleted object</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeletedObject_object
    {
        [EnumMember(Value = "app")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
        [EnumMember(Value = "customer")]
        #pragma warning disable CS1591
        Customer,
        #pragma warning restore CS1591
        [EnumMember(Value = "entitlement")]
        #pragma warning disable CS1591
        Entitlement,
        #pragma warning restore CS1591
        [EnumMember(Value = "offering")]
        #pragma warning disable CS1591
        Offering,
        #pragma warning restore CS1591
        [EnumMember(Value = "package")]
        #pragma warning disable CS1591
        Package,
        #pragma warning restore CS1591
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
    }
}
