// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>The store environment</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EnvironmentObject
    {
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
        [EnumMember(Value = "sandbox")]
        #pragma warning disable CS1591
        Sandbox,
        #pragma warning restore CS1591
    }
}
