// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListCustomerAttributes423Error_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "resource_locked_error")]
        #pragma warning disable CS1591
        Resource_locked_error,
        #pragma warning restore CS1591
    }
}
