// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MonetaryAmount : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Store commission or payment processor fees deducted from gross revenue (if any)</summary>
        public double? Commission { get; set; }
        /// <summary>ISO 4217 currency code</summary>
        public global::RevenueCat.Client.Models.Currency? Currency { get; set; }
        /// <summary>Total revenue generated (excluding taxes and commission)</summary>
        public double? Gross { get; set; }
        /// <summary>Net revenue after store commission / fees and taxes</summary>
        public double? Proceeds { get; set; }
        /// <summary>Estimated taxes deducted from gross revenue</summary>
        public double? Tax { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Models.MonetaryAmount"/> and sets the default values.
        /// </summary>
        public MonetaryAmount()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Models.MonetaryAmount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RevenueCat.Client.Models.MonetaryAmount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::RevenueCat.Client.Models.MonetaryAmount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "commission", n => { Commission = n.GetDoubleValue(); } },
                { "currency", n => { Currency = n.GetEnumValue<global::RevenueCat.Client.Models.Currency>(); } },
                { "gross", n => { Gross = n.GetDoubleValue(); } },
                { "proceeds", n => { Proceeds = n.GetDoubleValue(); } },
                { "tax", n => { Tax = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("commission", Commission);
            writer.WriteEnumValue<global::RevenueCat.Client.Models.Currency>("currency", Currency);
            writer.WriteDoubleValue("gross", Gross);
            writer.WriteDoubleValue("proceeds", Proceeds);
            writer.WriteDoubleValue("tax", Tax);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
