// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>Length of time during which metric data is collected in ISO 8601 format. Zero period means metric data was collected now</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OverviewMetric_period
    {
        [EnumMember(Value = "P0D")]
        #pragma warning disable CS1591
        P0D,
        #pragma warning restore CS1591
        [EnumMember(Value = "P28D")]
        #pragma warning disable CS1591
        P28D,
        #pragma warning restore CS1591
    }
}
