// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Package422Error_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unprocessable_entity_error")]
        #pragma warning disable CS1591
        Unprocessable_entity_error,
        #pragma warning restore CS1591
        [EnumMember(Value = "parameter_error")]
        #pragma warning disable CS1591
        Parameter_error,
        #pragma warning restore CS1591
        [EnumMember(Value = "store_error")]
        #pragma warning disable CS1591
        Store_error,
        #pragma warning restore CS1591
    }
}
