// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value. Always has the value `list`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductsFromEntitlement_object
    {
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
    }
}
