// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>The auto renewal status of a subscription.&lt;br&gt;&lt;br&gt;Possible values:&lt;br&gt;• `will_renew`: the subscription is currently set to automatically renew&lt;br&gt;• `will_not_renew`: the subscription is currently set to expire at the end of the period&lt;br&gt;• `will_change_product`: the subscription is currently set to change product at the end of the period (which might start a new subscription)&lt;br&gt;• `will_pause`: the subscription is currently set to pause at the end of the current period&lt;br&gt;• `requires_price_increase_consent`: the subscription will expire at the end of the current period unless the customer consents to the price increase&lt;br&gt;• `has_already_renewed`: the customer has already been charged for the upcoming renewal (so the renewal will take place even if the customer opts out of auto-renewal before the end of the period)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Subscription_auto_renewal_status
    {
        [EnumMember(Value = "will_renew")]
        #pragma warning disable CS1591
        Will_renew,
        #pragma warning restore CS1591
        [EnumMember(Value = "will_not_renew")]
        #pragma warning disable CS1591
        Will_not_renew,
        #pragma warning restore CS1591
        [EnumMember(Value = "will_change_product")]
        #pragma warning disable CS1591
        Will_change_product,
        #pragma warning restore CS1591
        [EnumMember(Value = "will_pause")]
        #pragma warning disable CS1591
        Will_pause,
        #pragma warning restore CS1591
        [EnumMember(Value = "requires_price_increase_consent")]
        #pragma warning disable CS1591
        Requires_price_increase_consent,
        #pragma warning restore CS1591
        [EnumMember(Value = "has_already_renewed")]
        #pragma warning disable CS1591
        Has_already_renewed,
        #pragma warning restore CS1591
    }
}
