// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace RevenueCat.Client.Models
{
    /// <summary>String representing the object&apos;s type. Objects of the same type share the same value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriptionTransaction_object
    {
        [EnumMember(Value = "subscription_transaction")]
        #pragma warning disable CS1591
        Subscription_transaction,
        #pragma warning restore CS1591
    }
}
