name: Build Android
on:
  push:
    branches-ignore: [main]
    paths:
      - app/**
      - .github/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: ./app/package-lock.json

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.2

      - name: Install
        run: npm ci
        working-directory: ./app
      - name: Prebuild
        run: npm run prebuild
        working-directory: ./app

      - name: Build Android
        run: ./gradlew build
        working-directory: ./app/android
