name: Publish API docker image to GitHub Container Registry
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  upload:
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: dotnet publish --os linux --arch x64 /t:PublishContainer -c Release
        working-directory: LiftLog.Api
      - name: Tag image
        run: docker tag liftlog-api:latest ghcr.io/liammorrow/liftlog:api
      - name: Push image
        run: docker push ghcr.io/liammorrow/liftlog:api
