import {
  ProgramBlueprint,
  Rest,
} from '@/models/blueprint-models';
import BigNumber from 'bignumber.js';
import { Duration, LocalDate } from '@js-joda/core';
import {
  toBigNumberJSON,
  toDurationJSON,
  toLocalDateJSON,
} from '@/models/storage/versions/latest';

export const BuiltInPrograms: Record<string, ProgramBlueprint> = {
  'a303c855-9ed7-4ff8-ae60-11e9a573193e': ProgramBlueprint.fromJSON({
    name: 'Starting Strength',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Workout A',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squat',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Bench Press',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Deadlift',
            sets: 1,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Workout B',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squat',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Overhead Press',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Deadlift',
            sets: 1,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
    ],
  }),

  'ac80c322-3c0f-42ba-b837-cd998adee25a': ProgramBlueprint.fromJSON({
    name: 'Stronglifts 5x5',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Workout A',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squat',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Bench Press',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Barbell Row',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Workout B',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squat',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Overhead Press',
            sets: 5,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Deadlift',
            sets: 1,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
    ],
  }),

  '347607f0-67b8-4051-bfc2-3b73fccf92d8': ProgramBlueprint.fromJSON({
    name: 'PPL',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Push',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Bench Press',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Overhead Press',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Tricep Extension',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Cable Fly',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Pull',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Deadlift',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Barbell Row',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Lat Pulldown',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Barbell Curl',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Legs',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squat',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Lunges',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Leg Extension',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Leg Curl',
            sets: 4,
            repsPerSet: 8,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
    ],
  }),

  '5072c29e-1de9-44e0-865f-f65a15e860f7': ProgramBlueprint.fromJSON({
    name: 'PHUL',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Upper Power',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Bench Press',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Barbell Row',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Overhead Press',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Lat Pulldown',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Barbell Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Tricep Extension',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Cable Fly',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Lower Power',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squat',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Deadlift',
            sets: 3,
            repsPerSet: 5,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Leg Press',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Leg Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Calf Raise',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Upper Hypertrophy',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Incline Bench Press',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Cable Row',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Dumbbell Fly',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Lat Pulldown',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Dumbbell Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Skullcrusher',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Lower Hypertrophy',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Front Squat',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Romanian Deadlift',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Leg Extension',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Leg Curl',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Calf Raise',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
    ],
  }),

  '0d0e0860-0555-4b43-bd93-350edd49c6bd': ProgramBlueprint.fromJSON({
    name: 'Light Calisthenics',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Push',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Dips',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Handstand Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Pull',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Pullups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Chinups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Inverted Rows',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Legs',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squats',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Lunges',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Calf Raises',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
    ],
  }),

  '890a285b-f883-4536-a1ce-cbc9e2d90399': ProgramBlueprint.fromJSON({
    name: 'Heavy Calisthenics',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Push',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Dips',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Handstand Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Planche Pushups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Pull',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Pullups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Chinups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Inverted Rows',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Muscle Ups',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
      {
        name: 'Legs',
        notes: '',
        exercises: [
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Squats',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Lunges',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Calf Raises',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
          {
            type: 'WeightedExerciseBlueprint',
            name: 'Pistol Squats',
            sets: 3,
            repsPerSet: 10,
            weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('0')),
            restBetweenSets: Rest.toJSON(Rest.medium),
            supersetWithNext: false,
            notes: '',
            link: '',
          },
        ],
      },
    ],
  }),
  '590a285b-f883-4536-a1ce-cdc9e2d90399': ProgramBlueprint.fromJSON({
    name: 'Cardio',
    lastEdited: toLocalDateJSON(LocalDate.of(2024, 1, 1)),
    sessions: [
      {
        name: 'Cardio A',
        notes: '',
        exercises: [
          {
            type: 'CardioExerciseBlueprint',
            name: 'Jogging',
            notes: '',
            link: '',
            sets: [
              {
                trackDuration: true,
                trackDistance: true,
                trackResistance: false,
                trackIncline: false,
                trackWeight: false,
                trackSteps: false,
                target: {
                  type: 'distance',
                  value: {
                    unit: 'metre',
                    value: toBigNumberJSON(new BigNumber(1200)),
                  },
                },
              },
            ],
          },
          {
            type: 'CardioExerciseBlueprint',
            name: 'Elliptical',
            notes: '',
            link: '',
            sets: [
              {
                trackDuration: true,
                trackDistance: true,
                trackResistance: false,
                trackIncline: false,
                trackWeight: false,
                trackSteps: false,
                target: {
                  type: 'time',
                  value: toDurationJSON(Duration.ofMinutes(30)),
                },
              },
            ],
          },
        ],
      },
    ],
  }),
};
