// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace RevenueCat.Client.Projects.Item.Apps.Item
{
    /// <summary>
    /// Roku Channel Store type details. Should only be used when type is roku.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithApp_PostRequestBody_roku : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Roku Pay API key provided on the Roku Pay Web Services page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RokuApiKey { get; set; }
#nullable restore
#else
        public string RokuApiKey { get; set; }
#endif
        /// <summary>Channel ID provided on the Roku Channel page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RokuChannelId { get; set; }
#nullable restore
#else
        public string RokuChannelId { get; set; }
#endif
        /// <summary>Channel name that is displayed on the Roku Channel page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RokuChannelName { get; set; }
#nullable restore
#else
        public string RokuChannelName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::RevenueCat.Client.Projects.Item.Apps.Item.WithApp_PostRequestBody_roku"/> and sets the default values.
        /// </summary>
        public WithApp_PostRequestBody_roku()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::RevenueCat.Client.Projects.Item.Apps.Item.WithApp_PostRequestBody_roku"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::RevenueCat.Client.Projects.Item.Apps.Item.WithApp_PostRequestBody_roku CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::RevenueCat.Client.Projects.Item.Apps.Item.WithApp_PostRequestBody_roku();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "roku_api_key", n => { RokuApiKey = n.GetStringValue(); } },
                { "roku_channel_id", n => { RokuChannelId = n.GetStringValue(); } },
                { "roku_channel_name", n => { RokuChannelName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("roku_api_key", RokuApiKey);
            writer.WriteStringValue("roku_channel_id", RokuChannelId);
            writer.WriteStringValue("roku_channel_name", RokuChannelName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
